version: 2.1

jobs:
  build:
    machine: true
    resource_class: nanophate/gcp-resource
    parallelism: 3
    steps:
      - checkout
      - run: |
          circleci tests glob /tmp/**/*.txt | circleci tests split --split-by=timings
      - store_test_results:
          path: test-results
